url: https://amira-david.com
baseurl: "" # Empty since it will be served from root

# Site settings
title: Amira & David
email: amira.e.david@gmail.com
description: "Invito Digitale | Invitación digital"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
# - title: twitter
#   url: http://twitter.com/jekyllrb
# - title: facebook
#   url:
# - title: stack-overflow
#   url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#   url: http://bitbucket.org/jekyll
# - title: github
#   url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

include: ["_it_pages", "_es_pages"]

port: 4001

# RSVP Form settings
rsvp_script_url: https://script.google.com/macros/s/AKfycbzefazSdQzutSUucdHRes6I2wjcJpruGmYnRzbFjfYL9KCoPfpDzQirEcRNdYB8iYRYDA/exec
rsvp_passkey: 8X4nP9$mK2#jL5vQ # This is just an example, use your own secure key
